volumes:
    prometheus_data: {}
services:
  service1:
    build: ./service1
    depends_on:
      - service2
    ports:
      - "8000:8000"
  service2:
    build: ./service2
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: service2
      MYSQL_USER: joe
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
  stastd:
    image: prom/statsd-exporter
    container_name: statsd
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./config/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
